name: FsegEnv
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - albumentations=1.2.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.0.0
  - cmake=3.22.1
  - colorama=0.4.5
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - cupy=11.3.0
  - cython=0.29.30
  - cytoolz=0.11.0
  - daal4py=2021.5.0
  - dask-core=2022.5.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distro=1.5.0
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=0.8.3
  - fastrlock=0.8
  - fonttools=4.25.0
  - freeglut=3.2.2
  - freetype=2.10.4
  - fsspec=2022.3.0
  - gettext=0.19.8.1
  - gitdb=4.0.10
  - glib=2.72.1
  - glib-tools=2.72.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - icu=70.1
  - imageio=2.9.0
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jasper=2.0.33
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.12
  - libffi=3.4.2
  - libglib=2.72.1
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libogg=1.3.4
  - libopencv=4.6.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libzlib=1.2.12
  - locket=1.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - networkx=2.7.1
  - ninja-base=1.10.2
  - notebook=6.4.11
  - opencv=4.6.0
  - openssl=1.1.1v
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pathtools=0.1.2
  - pcre=8.45
  - pickleshare=0.7.5
  - pip=22.1.2
  - ply=3.11
  - prometheus_client=0.13.1
  - promise=2.3
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - pure_eval=0.2.2
  - py-opencv=4.6.0
  - pycocotools=2.0.6
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.9
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - pywavelets=1.3.0
  - pywin32=302
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.4
  - qudida=0.0.4
  - requests=2.28.0
  - scikit-build=0.11.1
  - scikit-image=0.16.2
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2021.5.0
  - send2trash=1.8.0
  - sentry-sdk=1.11.1
  - setproctitle=1.2.2
  - shortuuid=1.0.11
  - sip=6.6.2
  - six=1.16.0
  - smmap=3.0.5
  - soupsieve=2.3.1
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tbb=2021.5.0
  - tensorboardx=2.2
  - terminado=0.13.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.11.2
  - torchaudio=0.12.0
  - torchmetrics=0.11.1
  - torchvision=0.13.0
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - unidecode=1.2.0
  - urllib3=1.26.9
  - wandb=0.13.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - icc_rt=2019.0.0
      - dal=2021.5.0
      - msys2-conda-epoch=20160418
      - vc=14.2
      - vc14_runtime=14.36.32532
      - vs2015_runtime=14.36.32532
      - winpty=0.4.3
      - m2w64-gcc-libgfortran=5.3.0
      - m2w64-gcc-libs=5.3.0
      - m2w64-gcc-libs-core=5.3.0
      - m2w64-gmp=6.1.0
      - m2w64-libwinpthread-git=5.0.0.4634.697f757
      - ucrt=10.0.20348.0
      - absl-py==1.1.0
      - annotated-types==0.6.0
      - anyio==3.7.1
      - cachetools==5.2.0
      - chardet==4.0.0
      - contourpy==1.1.0
      - cycler==0.10.0
      - easyocr==1.7.1
      - exceptiongroup==1.1.3
      - fastapi==0.103.2
      - gitpython==3.1.37
      - google-auth==2.9.1
      - google-auth-oauthlib==0.4.6
      - grpcio==1.47.0
      - h11==0.14.0
      - httptools==0.6.0
      - idna==2.10
      - importlib-metadata==4.12.0
      - importlib-resources==6.0.1
      - markdown==3.4.1
      - matplotlib==3.7.2
      - ninja==1.11.1.1
      - numpy==1.26.0
      - oauthlib==3.2.0
      - opencv-python-headless==4.8.0.76
      - pandas==2.1.1
      - pillow==9.5.0
      - protobuf==3.19.4
      - py-cpuinfo==9.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyclipper==1.3.0.post5
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pyparsing==2.4.7
      - python-bidi==0.4.2
      - python-dotenv==1.0.0
      - python-multipart==0.0.6
      - pytz==2023.3.post1
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - roboflow==1.1.4
      - rsa==4.8
      - scipy==1.11.2
      - seaborn==0.13.0
      - segment-anything==1.0
      - setuptools==68.2.2
      - shapely==2.0.2
      - sniffio==1.3.0
      - starlette==0.27.0
      - supervision==0.14.0
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - thop==0.1.1-2209072238
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - ultralytics==8.0.192
      - uvicorn==0.23.2
      - watchfiles==0.21.0
      - websockets==11.0.3
      - werkzeug==2.1.2
      - wget==3.2
      - zipp==3.8.1
      - pywinpty=2.0.2
prefix: C:\Users\taha.DESKTOP-BQA3SEM\anaconda3\envs\FsegEnv
